### PR TITLE
Clean up extension code

### PR DESCRIPTION
**Pull request by darkwing**
Some basic cleanups:

1.  We aren't checking for file extension case - fixed.
2.  rawUrl isn't hoisted, and actually doesn't need to exist
3.  else/if -- a file won't be .styl and .css

### CODE REVIEW

**Comment by openjck** [comment]
Awesome! Hate to be a nag, could we do a `beautify` before merging this?

**Comment by darkwing** [comment]
No problem, I just didn't know how to do it :/

**Comment by openjck** [comment]
No problem, it was more difficult than it should have been. I submitted #80 to fix that.

**Comment by openjck** [comment]
Looks great! Nice improvements. :clap:

**Pull request merged**
