### PR TITLE
Begin using deferreds with the Q module

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
Q

**Comment by darkwing** [comment]
Q

**Comment by openjck** [comment]
I lol'd :smile:

**Comment by HugoGiraudel** [comment]
Out-of-topic (or in-topic?): any reason why you use Q instead of Bluebird?

**Comment by darkwing** [comment]
@HugoGiraudel Inventors > Wildlife

**Comment by openjck** [comment]
> Out-of-topic (or in-topic?): any reason why you use Q instead of Bluebird?

Good question. Q appears to have the best support from the NPM community. It's actively maintained by two of the biggest module maintainers and gets 5,000,000 downloads per month.

**Comment by HugoGiraudel** [comment]
I remember reading some benchmarks showing how Q is the worst library for Promise regarding performance. Well, not the worst; there is one from jQuery below it. Bluebird is (was at the time of the benchmark at least) one of the fastest.

**Comment by HugoGiraudel** [comment]
Ah, here we go: https://github.com/cujojs/promise-perf-tests#test-results. :)

**Comment by openjck** [comment]
Very interesting. Thanks for sharing that.

There are definitely bottlenecks in posting a comment, including lots of network activity. I'm not sure users would notice the difference. Many will run off after submitting a pull request anyway, and not notice the compatibility comments until later. I'm happy to sacrifice some performance for a better-supported module.

**Comment by HugoGiraudel** [comment]
It's a trade-off. I won't tell you which to choose, just letting you know this so you can pick the right one for your product. :)

**Comment by openjck** [comment]
Definitely. I hadn't heard that about Q. Definitely something to keep in mind. Thanks for the link! :smile:

**Comment by HugoGiraudel** [comment]
Basically the reason behind the slowness of Q is that it freezes object, and in V8 frozen objects are extremely slow to being iterated (98% slower): http://stackoverflow.com/a/8435223.

**Comment by darkwing** [comment]
We'll keep an eye on performance, rolling with this for now, and adjusting in case of issue.

BTW @HugoGiraudel , do you have an alternative recommendation?

**Comment by HugoGiraudel** [comment]
I have heard nothing but the best about *Bluebird* but never tried it (7k+ stats on GitHub). *ES6 Promise Polyfill* by Jake Archibald would be good as well I suppose. And I've heard good things about *when* also.

**Pull request merged**
