### PR TITLE
Fix #100: Record installs with Postgres

### LINKED ISSUE #100: Measure number of initial installations

### PR DESCRIPTION
**Pull request by openjck**
How to test these changes:

1. Push this up to your personal Heroku
2. `heroku addons:create heroku-postgresql:hobby-dev`
3. Delete the webhook from your test repository
4. Re-add the test hook to your test repository
5. Verify that the ping was recorded
    1. `heroku pg:psql`
    2. `SELECT * FROM "Pings";`

### CODE REVIEW

**Comment by openjck** [comment]
Tests are failing, and I still want to add more. I'm trying to figure out how to do that now.

**Comment by darkwing** [comment]
We'll want some sort of test for this

**Comment by openjck** [comment]
Definitely. I'm investigating a good way to write tests. :smile:

**Comment by openjck** [comment]
Superseded by #147

**Pull request closed without merging**
