### PR TITLE
Add bin/www, a templating engine, and error pages

### PR DESCRIPTION
**Pull request by openjck**
These changes are related in that they work together to move us closer
to the setup that express-generator[1] recommends.

[1] https://www.npmjs.com/package/express-generator

### CODE REVIEW

**Comment by openjck** [comment]
Earlier discussion in #122.

**Comment by mrmakeit** [comment]
Looks good. R+

**Comment by darkwing** [comment]
R+, nice work!

**Comment by openjck** [comment]
Woo, awesome thanks! :smile:

**Pull request merged**
