### PR TITLE
Add Travis file to Discord

### PR DESCRIPTION
**Pull request by darkwing**
(Insert "I don't know what I'm doing" meme here)

This is a start...

### CODE REVIEW

**Comment by groovecoder** [comment]
You'll need to add Travis as a service in the repo settings too, right?

**Comment by darkwing** [comment]
Yep, I just added that.

**Comment by groovecoder** [comment]
Did you set it to test PRs too? Or just commits?

**Comment by groovecoder** [comment]
May need to ammend this commit and re-push it to get Travis to pick it up?

**Comment by darkwing** [comment]
"Build Pull Requests" is set to "On", yes

**Comment by darkwing** [comment]
https://travis-ci.org/mdn/discord

**Pull request merged**
