### PR TITLE
Template improvements

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
I went ahead and set the `TRACKING_ID` config variable on production now, so we don't need to worry about any extra steps at merge time.

**Comment by darkwing** [comment]
IMHO we should do a hostname sniff before calling the Google Analytics code.  i.e. we shouldn't load it on our local dev instances.

**Comment by openjck** [comment]
Will do

**Comment by openjck** [comment]
Updated! :smile:

**Comment by darkwing** [comment]
Love it! :) R+

**Pull request merged**
