### PR TITLE
Only supporting pull_request allows us to shorten code

### PR DESCRIPTION
**Pull request by darkwing**
We can make our code much shorter if we're only planning to support pull requests...

This is all up for discussion

### CODE REVIEW

**Comment by mrmakeit** [comment]
I'd think keeping the push compatable code would assist those that use this on repos that they commit directly to.  I know I'm using it.

**Comment by groovecoder** [comment]
I like having simpler focused code & feature first and then waiting for users to ask for more features.

**Comment by openjck** [comment]
I agree. Even better, finding the need for a feature through research.

Pull request comments are going to be great for projects with multiple team members. For projects with only one contributor, using the `doiuse` client on the command line or in Gulp might be better. The goal is to report on the mistakes before they're made.

**Comment by darkwing** [comment]
We could add a ".discord" file, JSON-format, which holds settings on a per-repo basis, like if the user sometimes wants to check each commit.

In the end, I think that checking individual commits is going to be exhausting for our system.

**Comment by openjck** [comment]
Agreed. We could do that, and support other uses through settings, but I don't see a strong justification for complicating the project. Pull request reporting works fine for Travis, Jenkins, and Code Climate.

**Pull request merged**
