### PR TITLE
added log messages for parsed files and commits

### PR DESCRIPTION
**Pull request by federicoculloca**
Also, better error reporting

### CODE REVIEW

**Comment by darkwing** [comment]
To be consistent for each comment, we should add `"{label}: " + var` -- you're missing the colon

#nit

**Comment by openjck** [comment]
Thanks @federicoculloca!

These are some nice improvements. We're doing some refactoring this week. Would it be okay if we take another look at this and other major changes after that's done? I hate to delay, it's just that merging features into the refactor would be thorny.

Otherwise this looks great! :smile:

**Comment by federicoculloca** [comment]
Sure, no problem :)

**Comment by openjck** [comment]
Thanks so much!

**Comment by openjck** [comment]
Thanks for waiting, Federico. The major refactoring is done, so the source code should be much more stable now if you're still interested in contributing. :smile:

**Comment by federicoculloca** [comment]
Yes, I'm still interested.
I'll take a look when time permits, thanks :)

Il 07 luglio 2015 17:54:15 CEST, John Karahalis <notifications@github.com> ha scritto:

**Comment by darkwing** [comment]
Forgive me @federicoculloca but I'm going to close this for now -- feel free to fix and reopen in the future!

**Comment by federicoculloca** [comment]
@darkwing don't worry, I really didn't have time to work on this right now anyway. I'll reopen and work on this when time permits.

**Pull request closed without merging**
