### PR TITLE
Fix issue 70 - Improve logger functions

### PR DESCRIPTION
**Pull request by darkwing**
Smaller, sweeter logging functions.

```
logger.log('whatever');
logger.warn('whatever else');
logger.error('oh noooo');

logger.error('one', 'two', 'three');
```

### CODE REVIEW

**Comment by openjck** [comment]
Looks great! Just a few small things:

* It would be great if we could update [line 92 of hook.js](https://github.com/darkwing/Discord/blob/update-logs/hook.js#L92) so that the arguments are printed in the correct order.
* Do we want to prefix messages like that with *Debug:*? There is some true debugging in the codebase (like on [line 27](https://github.com/darkwing/Discord/blob/update-logs/hook.js#L27)) but other places where we just want to log usage.
* Total nitpick, but can we remove the spaces after each label so that there is only one space between label and message?
* The beautify task (`gulp --gulpfile gulpfiles/dev.js beautify`) does some weird things to the single-line objects. Setting `keepArrayIndentation` to `true` in the Gulpfile would be an improvement, or we could format that code differently. The beautifier isn't perfect, but it would be great to keep using it so that we don't get into a situation where we need to reformat code manually later.

**Comment by darkwing** [comment]
Updated!

**Comment by openjck** [comment]
Awesome!

How about the `beautify` task? Also, is there a way we could print true log messages (Like *Test requested from XYZ*) without prefixing it with *[debug]*?

**Comment by darkwing** [comment]
Why wouldn't we want to prefix?  My thought was that it's important to qualify the level within the log.

**Comment by openjck** [comment]
Definitely. I think prefixing is great. It would definitely help us to better search and understand the logs. Is the prefix *[debug]* accurate for the message about a repository requesting a test, though? We're using that as a stand-in for database logging rather than debugging.

**Comment by openjck** [comment]
Beautiful! Thanks for the updates. This is great.

**Pull request merged**
