### PR TITLE
Begin shrink-wrapping dependencies

### PR DESCRIPTION
**Pull request by openjck**
The built-in "shrinkwrap" command is used. I also considered
npm-shrinkwrap [1] and lockdown [2] but encountered problems with both
during testing. The built-in "shrinkwrap" command is less robust, but
more stable.

[1] https://www.npmjs.com/package/npm-shrinkwrap
[2] https://www.npmjs.com/package/lockdown

### CODE REVIEW

**Comment by openjck** [comment]
Some more information on what `shrinkwrap` is all about:

https://docs.npmjs.com/cli/shrinkwrap

**Comment by mrmakeit** [comment]
shrinkwrap is intended for published packages.  Is there a reason we want to lock out dependencies versions?  Something like doiuse probably should use the latest version, so that it is in line with caniuse.

**Comment by openjck** [comment]
Just wanted to keep things as stable and reproducible as possible. Does the doiuse module needed to be updated to use the latest caniuse data?

**Comment by mrmakeit** [comment]
Yes

**Comment by mrmakeit** [comment]
And shrinkwrap will fix the caniuse database either way.

**Comment by openjck** [comment]
Ah, nice catch. You're right! I'll replace this with a PR to standardize the flexible version numbers. (I hadn't been using them because I was planning this PR.)

**Pull request closed without merging**
