### PR TITLE
Replace Procfile with npm start script

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by groovecoder** [comment]
This feels dirty ...

**Comment by openjck** [comment]
I can see how it might look strange. I was surprised to find it's a common convention. It's what Heroku uses [in their documentation](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process) and also what [express-generator](https://www.npmjs.com/package/express-generator) sets up.

**Comment by groovecoder** [comment]
:+1:

**Comment by darkwing** [comment]
R+, worked for me!

**Pull request merged**
